# Site settings
author: Cheng Vue
title: Coming Together Is A Beginning; Working Together Is Success
header-img: img/home-bg.png
email: csalvue@gmail.com
copyright_name: Cheng Vue
description: > # this means to ignore newlines until "baseurl:"
  Journey to Become a Full Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cheng0315

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
